name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package and dependencies
      run: |
        pip install -e ".[dev]"
    - name: Lint
      run: |
        python3 -m black -t py38 --exclude=duolingo_sync/duolingo.py --check .
    - name: Test with pytest
      run: |
        pytest
